name = "XLSXasJSON"
uuid = "8c9e00cc-ccf1-11e8-3de6-5b028f480d9e"
author = ["김용희 <yongheekim@devsisters.com>"]
version = "0.4.1"

[deps]
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
JSONPointer = "cc3ff66e-924d-4e6b-b111-1d9960e4bba9"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"

[compat]
JSON3 = "1"
JSONPointer = "0.3"
OrderedCollections = "1"
XLSX = "^0.5.8, 0.7"
julia = "^1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
