name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Install snapd
      run: |
        echo Install snapd
        sudo apt update
        sudo apt install snapd
    - name: Install Julia
      run: |
        echo Install Julia
        sudo snap install julia --classic
    - name: Install XLSXasJSON
      run: |
              julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/devsisters/XLSXasJSON.jl"))'
    - name: Test
      run: |
              julia -e 'using Pkg; Pkg.test("XLSXasJSON")
